# Generated by Django 4.1.3 on 2022-12-14 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RobotTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=250)),
                ('image_url', models.URLField(verbose_name='Image URL')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='AppRobots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robot_name', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=250)),
                ('available_quantity', models.PositiveIntegerField()),
                ('image_url', models.URLField(verbose_name='Image URL')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robots.robottypes')),
            ],
        ),
    ]
