# Generated by Django 4.1.3 on 2022-12-14 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_appuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='username',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
